name: Telegram Bot

on:
  schedule:
    - cron: '0 */5 * * *'
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install python-telegram-bot
      - name: Run bot
        run: timeout 17000 python bot.py || true
